name: Laravel

on:
  push:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env
        run: |
          cd src
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker images
        run: |
          docker-compose up -d 

      - name: list
        run: |
            docker-compose ps

      - name: Installation of dependencies
        run: |
          docker-compose exec -T --user root php composer install

      - name: Generate key
        run: |
          docker-compose exec -T --user root php php artisan key:generate
          
      - name: Run Tests
        run: |
          docker-compose exec -T --user root php php artisan test

          
      - name: Run Tests
        run: |
          docker-compose exec -T --user root php php artisan octane:start