name: Laravel

on:
  push:
    branches: [ "master" ]

    
jobs:
  laravel-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t my-php-app:latest -f dockerfiles/php.dockerfile .
          docker build -t my-nginx-app:latest -f dockerfiles/nginx.dockerfile .

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          sleep 30 # Adjust as needed to wait for services to be ready

      - name: Run tests
        run: |
          docker exec docker-beneficiary-php php artisan test

      - name: Tear down Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
